### ISSUE TITLE
Save resulting depth video?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [ibaiGorordo/ONNX-PackNet-SfM#1]
Thanks for sharing your implementation!  
How would one go about saving a .mp4 of the depth output from video_depth_estimation.py?   In other words, how did you create your side by side video example?

**Comment by ibaiGorordo** [comment]
You only need three lines:
- `out = cv2.VideoWriter('output.avi',cv2.VideoWriter_fourcc('M','J','P','G'), 20, (1280*2,720))` before the while loop
- `out.write(combined_img)` after the imshow
- `out.release()` after cap.release.

Depending on your video size, you might have to modify the resolution of the video, otherwise it will not write the video. You can also search how to write video with opencv and you will get more information.
